@extends('layouts.equip')

@section('title', __("Detall d'Estadi"))

@section('content')
  <x-estadi
    :nom="$estadi->nom"
    :capacitat="$estadi->capacitat"
    :equips="$estadi->equips"
  />
@endsection

<div class="mt-8 p-6 bg-blue-50 rounded-lg border border-blue-100 shadow-inner">
    <h3 class="text-xl font-bold text-blue-900 mb-3 flex items-center gap-2">
        ✨ {{ __('Descripció intel·ligent') }}
    </h3>

    @if(!empty($descripcio))
        <p class="text-gray-800 leading-relaxed italic">"{{ $descripcio }}"</p>
    @else
        <p class="text-gray-500 italic">{{ __('No s’ha pogut generar la descripció ara mateix.') }}</p>
    @endif
    
    <p class="text-xs text-blue-400 mt-4 font-mono uppercase tracking-widest">
        Generated by Local AI (Ollama)
    </p>
</div>